__title__ = 'dwiqc'
__description__ = 'Quality Assurance Pipeline for Diffusion MR Data'
__url__ = 'https://github.com/harvard-nrg/dwiqc'
__version__ = '0.4.17'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
