prequal:
  shell:
    - '--eddy_cuda'
    - '10.2'
    - 'j'
    - '--num_threads'
    - '2'
    - '--denoise'
    - 'on'
    - '--degibbs'
    - 'off'
    - '--rician'
    - 'off'
    - '--prenormalize'
    - 'on'
    - '--correct_bias'
    - 'on'
    - '--topup_first_b0s_only'
